### ISSUE TITLE
Specify more types in the method signatures

### ISSUE THREAD

**Issue by MOZGIII** [DanielHreben/jest-mock-server#188]
TypeScript has hard time guessing the types, it would be nice if you could add types explicitly, such that `ctx` is typed accordingly:

![image](https://user-images.githubusercontent.com/265507/143579075-5f9e6d22-94c5-4dbc-a89f-675914575b57.png)

**Comment by MOZGIII** [comment]
The desired effect would be reached of you simply move `@types/koa-bodyparser`, `@types/koa-router` and `@types/koa` to the `dependencies`.

**Comment by MOZGIII** [comment]
Also, the code apparently needs `tslib` which doesn't exist in the `dependencies`.

**Comment by DanielHreben** [comment]
I released a new version, please check if those issues are resolved now

**Comment by MOZGIII** [comment]
Hey, I don't think I'll get to that as I've lost track of where I used it. Pretty sure that if you have a proper type in a similar situation as on the screenshot - the fix is good.
